# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: DeployHookRender
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore ./CodeCodexBackend/CodeCodexBackend/CodeCodexBackend.csproj
    - name: Format
      run: dotnet format ./CodeCodexBackend/CodeCodexBackend/CodeCodexBackend.csproj --verify-no-changes  
    - name: Build
      run: dotnet build ./CodeCodexBackend/CodeCodexBackend/CodeCodexBackend.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./CodeCodexBackend/CodeCodexBackend/CodeCodexBackend.csproj --configuration Release --no-build
      
    - name: Deploy
      env:
        DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
      run: curl -X POST "$DEPLOY_HOOK"
